name: Cygwin Distcheck

on:
  # Allow this workflow to be called from another workflow
  workflow_call:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
    - name: Set git to Linux line endings
      run: git config --global core.autocrlf input
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - name: Cache Cygwin packages
      uses: actions/cache@v5
      with:
        path: C:\cygwin-packages
        key: cygwin-${{ runner.os }}-${{ hashFiles('.github/workflows/**') }}
    - name: Install cygwin
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          autoconf automake make libtool flex gperf
          gcc-core
          lzip xz
          gettext-devel libffi-devel libgc-devel
          libgmp-devel libreadline-devel libunistring-devel
          libiconv-devel
          texinfo texinfo-tex texlive
    - name: Configure
      run: |
          export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
          mkdir "$(pwd)/app"
          echo "3.0.99" > .tarball_version
          sed -i 's/^GUILE_MICRO_VERSION=.*/GUILE_MICRO_VERSION=99/' GUILE-VERSION
          sed -i 's|m4_esyscmd(\[build-aux/git-version-gen[^]]*\])|[3.0.99]|g' configure.ac
          ./autogen.sh
          ./configure CFLAGS="-g -O2 -Wall" --prefix="$(pwd)/app"
      shell: C:\cygwin\bin\bash.exe -o igncr '{0}'
    - name: Build
      run: make -j"$(nproc)" V=1 2>&1 | tee build.log
      shell: C:\cygwin\bin\bash.exe -o igncr '{0}'
    - name: Run Dist Check
      run: |
        sed -i "s/^VERSION=.*/VERSION='3.0.99'/" configure
        sed -i "s/^PACKAGE_VERSION=.*/PACKAGE_VERSION='3.0.99'/" configure
        sed -i "s/^PACKAGE_STRING=.*/PACKAGE_STRING='GNU Guile 3.0.99'/" configure
        if [ -f GNUmakefile ]; then
          sed -i $'s/^[[:space:]]*_curr-ver := .*/\t_curr-ver := $(VERSION)/' GNUmakefile
        fi
        make -j"$(nproc)" distcheck V=1
      shell: C:\cygwin\bin\bash.exe -o igncr '{0}'
    - name: Archive Source Package
      uses: actions/upload-artifact@v6
      with:
        name: Source Package
        path: |
          guile*.tar
          ./*.log
          ./**/*.log
