name: MinGW

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: MINGW64, env: x86_64,       thread: --without-threads, jit: --enable-jit=no,  gmp: --enable-mini-gmp, s64: --without-64-calls }
          - { sys: MINGW32, env: i686,         thread: --without-threads, jit: --enable-jit=yes, gmp: --enable-mini-gmp, s64: --without-64-calls }
          - { sys: UCRT64,  env: ucrt-x86_64,  thread: --without-threads, jit: --enable-jit=no,  gmp: --enable-mini-gmp, s64: --without-64-calls }
          - { sys: CLANG64, env: clang-x86_64, thread: --without-threads, jit: --enable-jit=no,  gmp: --enable-mini-gmp, s64: --without-64-calls }

    runs-on: windows-latest
    name: Build ${{matrix.sys}} ${{matrix.env}} ${{matrix.thread}} ${{matrix.jit}} ${{matrix.gmp}} ${{matrix.s64}}
    timeout-minutes: 150
    permissions:
      contents: read

    steps:
    - name: Set git to Linux line endings
      run: git config --global core.autocrlf input

    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        cache: true
        install: >-
          autotools
          base-devel
          mingw-w64-${{matrix.env}}-toolchain
          flex
          gperf
          lzip xz
          pkgconf
          mingw-w64-${{matrix.env}}-gettext
          mingw-w64-${{matrix.env}}-gmp
          mingw-w64-${{matrix.env}}-libffi
          mingw-w64-${{matrix.env}}-gc
          mingw-w64-${{matrix.env}}-libiconv
          mingw-w64-${{matrix.env}}-readline
          mingw-w64-${{matrix.env}}-libunistring
          texinfo

    - name: Configure
      run: |
        export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
        mkdir "$(pwd)/app"
        sed -i 's/^/;;/' test-suite/tests/version.test
        ./autogen.sh
        ./configure CFLAGS="-g -O2 -Wall" ${{matrix.thread}} ${{matrix.jit}} ${{matrix.gmp}} ${{matrix.s64}} --prefix="$(pwd)/app"
      shell: msys2 -o igncr '{0}'

    - name: Build
      run: make -j"$(nproc)" V=1 2>&1 | tee build.log
      shell: msys2 -o igncr '{0}'

    - name: Run Unit Tests
      run: make check V=1
      shell: msys2 -o igncr '{0}'

    - name: Archive Test Logs
      if: success() || failure()
      uses: actions/upload-artifact@v6
      with:
        name: mingw ${{matrix.sys}}-${{matrix.env}}${{matrix.thread}}${{matrix.jit}}${{matrix.gmp}}${{matrix.s64}}
        path: |
          ./*.log
          ./**/*.log
