name: MSYS

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    timeout-minutes: 90
    permissions:
      contents: read
    steps:
    - name: Set git to Linux line endings
      run: git config --global core.autocrlf input

    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        cache: true
        install: >-
          autotools
          gcc
          flex
          gperf
          lzip xz
          pkgconf
          gettext-devel
          gmp-devel
          libffi-devel
          libgc-devel
          libiconv-devel
          libintl
          libreadline-devel
          libunistring-devel
          texinfo

    - name: Configure
      run: |
        export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
        mkdir "$(pwd)/app"
        sed -i 's/^/;;/' test-suite/tests/version.test
        ./autogen.sh
        ./configure CFLAGS="-g -O2 -Wall" --prefix="$(pwd)/app"
      shell: msys2 -o igncr '{0}'

    - name: Build
      run: make -j"$(nproc)" V=1 2>&1 | tee build.log
      shell: msys2 -o igncr '{0}'

    - name: Run Unit Tests
      run: make check V=1
      shell: msys2 -o igncr '{0}'

    - name: Archive Test Logs
      if: success() || failure()
      uses: actions/upload-artifact@v6
      with:
        name: Test Logs
        path: |
          ./*.log
          ./**/*.log
