name: Ubuntu Distcheck

on:
  # Allow this workflow to be called from another workflow
  workflow_call:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to checkout'
        default: 'spk121/guile'
        required: false
        type: string
      ref:
        description: 'Git ref to checkout'
        default: ''
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - name: Cache apt packages
      uses: actions/cache@v5
      with:
        path: /var/cache/apt/archives
        key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/**') }}
    - name: Install packages
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        texlive
        texlive-plain-generic
        texinfo
        autoconf
        libtool
        gettext
        autopoint
        gperf
        pkg-config
        lzip
        libgc-dev
        libgmp-dev
        libltdl-dev
        libncurses5-dev
        libreadline-dev
        libunistring-dev
    - name: Configure
      run: |
        export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
        mkdir `pwd`/app
        echo "3.0.99" > .tarball_version
        sed -i s/^GUILE_MICRO_VERSION=.*/GUILE_MICRO_VERSION=99/ GUILE-VERSION
        sed -i 's|m4_esyscmd(\[build-aux/git-version-gen[^]]*\])|[3.0.99]|g' configure.ac
        ./autogen.sh
        ./configure CFLAGS="-g -O2 -Wall" --prefix=`pwd`/app
    - name: Build
      run: make -j$(nproc) V=1
    - name: Check
      run: make check V=1
    - name: Run Dist Check
      run: make -j$(nproc) distcheck V=1
    - name: Decompress gzip tarball
      # upload-artifact always zips its output, so decompress the .tar.gz
      # to avoid double-compression.
      run: gunzip guile-*.tar.gz
    - name: Archive Source Package
      uses: actions/upload-artifact@v6
      with:
        name: Source Package
        path: |
          guile-*.tar
          ./*.log
          ./**/*.log
